// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA12DrqR8whzZ8CczwuSL7JB50oPsoEzRc',
    appId: '1:813893921216:web:8a50d6424b4143400a8025',
    messagingSenderId: '813893921216',
    projectId: 'ahilyanagar-corporation-14760',
    authDomain: 'ahilyanagar-corporation-14760.firebaseapp.com',
    storageBucket: 'ahilyanagar-corporation-14760.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUlHx3u6-0DBoaqVvr16F47ZPyaTicpHk',
    appId: '1:813893921216:android:5abe7fb6c7775efe0a8025',
    messagingSenderId: '813893921216',
    projectId: 'ahilyanagar-corporation-14760',
    storageBucket: 'ahilyanagar-corporation-14760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRZK0WEH3xBME91AMm2SBJEL76MHZQjW0',
    appId: '1:813893921216:ios:d8f881d3c3ad80fd0a8025',
    messagingSenderId: '813893921216',
    projectId: 'ahilyanagar-corporation-14760',
    storageBucket: 'ahilyanagar-corporation-14760.firebasestorage.app',
    iosBundleId: 'com.example.ahilyanagar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRZK0WEH3xBME91AMm2SBJEL76MHZQjW0',
    appId: '1:813893921216:ios:d8f881d3c3ad80fd0a8025',
    messagingSenderId: '813893921216',
    projectId: 'ahilyanagar-corporation-14760',
    storageBucket: 'ahilyanagar-corporation-14760.firebasestorage.app',
    iosBundleId: 'com.example.ahilyanagar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA12DrqR8whzZ8CczwuSL7JB50oPsoEzRc',
    appId: '1:813893921216:web:21ebde35b3c92ffd0a8025',
    messagingSenderId: '813893921216',
    projectId: 'ahilyanagar-corporation-14760',
    authDomain: 'ahilyanagar-corporation-14760.firebaseapp.com',
    storageBucket: 'ahilyanagar-corporation-14760.firebasestorage.app',
  );

}